name: mnist_pl
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10
  - pytorch
  - torchvision
  - torchaudio
  - cpuonly
  - pandas
  - matplotlib
  - numpy
  - pip
  - pip:
      - pytorch-lightning
      - torchmetrics